from typing import Final
import numpy as np
import numpy.typing as npt

ACTION_SPACE_SIZE: Final[int]
ACTION_EXCHANGE_TILE_OFFSET: Final[int]
ACTION_CHOOSE_MISSING_OFFSET: Final[int]
ACTION_DISCARD_OFFSET: Final[int]
ACTION_HU: Final[int]
ACTION_PONG: Final[int]
ACTION_EXPOSED_KONG: Final[int]
ACTION_CONCEALED_KONG_OFFSET: Final[int]
ACTION_ADDED_KONG_OFFSET: Final[int]
ACTION_PASS: Final[int]
LEGAL_ACTION_MASK_WORDS: Final[int]
STEP_RECORD_WIDTH: Final[int]
TILE_OBSERVATION_WIDTH: Final[int]
TILE_OBSERVATION_PLANES: Final[int]
MELD_OBSERVATION_WIDTH: Final[int]
MELD_SLOTS: Final[int]
MELD_FIELDS: Final[int]
RIVER_OBSERVATION_WIDTH: Final[int]
RIVER_TILE_CAPACITY: Final[int]
RIVER_FIELDS: Final[int]
META_OBSERVATION_WIDTH: Final[int]
PLAYER_COUNT: Final[int]
TILE_KIND_COUNT: Final[int]
PHASE_EXCHANGE: Final[int]
PHASE_CHOOSE_MISSING: Final[int]
PHASE_TURN: Final[int]
PHASE_HU_RESPONSE: Final[int]
PHASE_MELD_RESPONSE: Final[int]
PHASE_FINISHED: Final[int]

class Game:
    def __init__(self, seed: int = 0) -> None: ...
    @staticmethod
    def with_exchange_direction(seed: int, direction: int) -> Game: ...
    def reset(self, seed: int) -> None: ...
    @property
    def phase(self) -> int: ...
    @property
    def decision(self) -> tuple[int, int] | None: ...
    @property
    def legal_action_mask(self) -> tuple[int, int]: ...
    def step_id(self, action: int) -> tuple[int, ...]: ...
    def step_into(self, action: int, output: npt.NDArray[np.int64]) -> None: ...
    @property
    def dealer(self) -> int: ...
    @property
    def exchange_direction(self) -> int: ...
    @property
    def wall_remaining(self) -> int: ...
    @property
    def current_draw(self) -> tuple[int, int, bool] | None: ...
    def concealed_into(self, seat: int, output: npt.NDArray[np.uint8]) -> None: ...
    def locked_into(self, seat: int, output: npt.NDArray[np.uint8]) -> None: ...
    def exchange_selection_into(self, seat: int, output: npt.NDArray[np.uint8]) -> None: ...
    def scores(self) -> tuple[int, int, int, int]: ...
    def missing_suits(self) -> tuple[int, int, int, int]: ...
    def has_won(self, seat: int) -> bool: ...
    def max_win_multipliers(self) -> tuple[int, int, int, int]: ...
    def melds(self, seat: int) -> list[tuple[int, int, int]]: ...
    def discards(self) -> list[tuple[int, int]]: ...
    def rankings(self) -> tuple[int, int, int, int]: ...

class Batch:
    def __init__(self, size: int, seed: int = 0) -> None: ...
    def __len__(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    def reset_all(self, seed: int) -> None: ...
    def reset_at(self, index: int, seed: int) -> None: ...
    def reset_many(
        self,
        indices: npt.NDArray[np.uint32],
        seeds: npt.NDArray[np.uint64],
    ) -> None: ...
    def legal_action_masks_into(self, output: npt.NDArray[np.uint64]) -> None: ...
    def step_into(
        self,
        actions: npt.NDArray[np.uint8],
        records: npt.NDArray[np.int64],
    ) -> None: ...
    def observe_into(
        self,
        tile_obs: npt.NDArray[np.uint8],
        melds: npt.NDArray[np.uint8],
        river: npt.NDArray[np.uint8],
        meta: npt.NDArray[np.int32],
    ) -> None: ...
    def step_and_observe_into(
        self,
        actions: npt.NDArray[np.uint8],
        records: npt.NDArray[np.int64],
        mask_words: npt.NDArray[np.uint64],
        tile_obs: npt.NDArray[np.uint8],
        melds: npt.NDArray[np.uint8],
        river: npt.NDArray[np.uint8],
        meta: npt.NDArray[np.int32],
    ) -> None: ...
